GET http://localhost:3000/rides
###############################

PATCH http://localhost:3000/train/S100
Content-Type: application/json

{
    "accessible":true,
    "seats":3000,
    "desc":"test"
}
################################

DELETE http://localhost:3000/carsssss/2
################################

POST http://localhost:3000/train
Content-Type: application/json

{
    "name":"S100",
    "accessible":false,
    "seats":0,
    "desc":"aaaaaaaaaaa"
}
################################