GET http://localhost:3000/rides
###############################

PATCH http://localhost:3000/train/S100
Content-Type: application/json

{
    "train":{
        "barrierefrei":true,
        "plaetze":3000,
        "beschreibung":"test1"
    }
}
################################
PATCH http://localhost:3000/station/AAAAA
Content-Type: application/json

{
    "station":{
        "kuerzel":"BBBBB",
        "name":"Test1",
        "standort":"loc1"
    }
}
################################

DELETE http://localhost:3000/ride/8
################################
DELETE http://localhost:3000/train/S100
################################
DELETE http://localhost:3000/station/BBBBB
################################

POST http://localhost:3000/train
Content-Type: application/json

{
    "name":"S100",
    "accessible":false,
    "seats":0,
    "desc":"aaaaaaaaaaa"
}
################################
POST http://localhost:3000/station
Content-Type: application/json

{
    "abbr":"AAAAA",
    "name":"Test",
    "location":"loc"
}
################################
POST http://localhost:3000/ride
Content-Type: application/json

{
    "stationFrom":"BBBBB",
    "stationTo":"JJDIJ",
    "departTime":"00:00:00",
    "arrivalTime":"00:15:00"
}